from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import cv2
import numpy as np

from .analysis import load_image_for_output, save_event_analysis
from .events import (
    generate_events_from_flow,
    save_event_preview,
    save_event_stream_gif,
    save_events_csv,
    save_motion_preview_from_flow_gif,
)
from .semantics import PALETTE, REGION_LABELS


def run_arbitrary_optical_flow(
    output_dir: Path,
    image_rgb: np.ndarray,
    semantic_mask: np.ndarray,
    blob_map: np.ndarray,
    blob_metadata: list[dict],
    debug_subdir_name: str = "arbitrary_optical_flow",
    duration_ms: float = 140.0,
    magnitude_px: float = 5.5,
    seed: int = 7,
) -> dict[str, Any]:
    debug_dir = output_dir / debug_subdir_name
    debug_dir.mkdir(parents=True, exist_ok=True)

    flow_x, flow_y = build_arbitrary_face_flow(semantic_mask, magnitude_px=magnitude_px, seed=seed)
    threshold_map = np.full(semantic_mask.shape, 0.075, dtype=np.float32)
    threshold_map[semantic_mask == 0] = 1.0

    events = generate_events_from_flow(
        image_rgb,
        blob_map,
        blob_metadata,
        flow_x,
        flow_y,
        threshold_map=threshold_map,
        duration_ms=duration_ms,
        steps=16,
        max_events_per_step=5000,
    )

    np.save(debug_dir / "flow_x.npy", flow_x)
    np.save(debug_dir / "flow_y.npy", flow_y)
    np.save(debug_dir / "events.npy", events)
    save_events_csv(debug_dir / "events.csv", events)
    save_event_preview(debug_dir / "event_frame_preview.png", semantic_mask.shape, events)
    save_flow_overlay(debug_dir / "arbitrary_flow_overlay.png", image_rgb, semantic_mask, flow_x, flow_y)
    save_motion_preview_from_flow_gif(debug_dir / "motion_preview.gif", image_rgb, flow_x, flow_y)
    save_motion_preview_from_flow_gif(
        debug_dir / "motion_preview_foreground_rgb.gif",
        image_rgb,
        flow_x,
        flow_y,
        foreground_mask=semantic_mask > 0,
        background_mode="foreground_rgb",
    )
    save_event_stream_gif(debug_dir / "event_stream_black.gif", image_rgb, events, background_mode="black")
    save_event_stream_gif(debug_dir / "event_stream.gif", image_rgb, events)

    stats = save_event_analysis(debug_dir, image_rgb, semantic_mask, blob_map, blob_metadata, events)
    summary = {
        "mode": "arbitrary_optical_flow",
        "duration_ms": float(duration_ms),
        "magnitude_px": float(magnitude_px),
        "seed": int(seed),
        "num_events": int(len(events)),
        "flow": {
            "mean_magnitude_px": float(np.sqrt(flow_x * flow_x + flow_y * flow_y)[semantic_mask > 0].mean()),
            "max_magnitude_px": float(np.sqrt(flow_x * flow_x + flow_y * flow_y).max()),
        },
        "statistics": stats,
    }
    (debug_dir / "debug_summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    return summary


def run_semantic_mask_focused_flow(
    output_dir: Path,
    image_rgb: np.ndarray,
    semantic_mask: np.ndarray,
    blob_map: np.ndarray,
    blob_metadata: list[dict],
    debug_subdir_name: str = "semantic_mask_flow",
    duration_ms: float = 140.0,
    magnitude_px: float = 4.0,
) -> dict[str, Any]:
    debug_dir = output_dir / debug_subdir_name
    debug_dir.mkdir(parents=True, exist_ok=True)

    # This is the current main debug path: semantic_mask.npy directly controls
    # the synthetic optical flow for each face part.
    flow_x, flow_y, region_motion = build_semantic_region_flow(semantic_mask, magnitude_px=magnitude_px)

    # Event threshold is only permissive on semantic foreground. Background is
    # assigned a high threshold and generate_events_from_flow also requires a
    # foreground blob id, so background events stay at zero.
    threshold_map = np.full(semantic_mask.shape, 0.075, dtype=np.float32)
    threshold_map[semantic_mask == 0] = 1.0

    # Events are generated by warping the image through this flow and comparing
    # adjacent warped frames, not by painting events manually.
    events = generate_events_from_flow(
        image_rgb,
        blob_map,
        blob_metadata,
        flow_x,
        flow_y,
        threshold_map=threshold_map,
        duration_ms=duration_ms,
        steps=16,
        max_events_per_step=5000,
    )

    np.save(debug_dir / "flow_x_2.npy", flow_x)
    np.save(debug_dir / "flow_y_2.npy", flow_y)
    np.save(debug_dir / "events_mask_flow_2.npy", events)
    save_events_csv(debug_dir / "events_mask_flow_2.csv", events)
    save_event_preview(debug_dir / "event_frame_preview_mask_flow_2.png", semantic_mask.shape, events)
    save_semantic_region_flow_overlay(
        debug_dir / "semantic_region_flow_overlay_2.png",
        image_rgb,
        semantic_mask,
        flow_x,
        flow_y,
    )
    save_flow_magnitude_png(debug_dir / "semantic_region_flow_magnitude_2.png", semantic_mask, flow_x, flow_y)
    save_motion_preview_from_flow_gif(
        debug_dir / "motion_preview_mask_2.gif",
        image_rgb,
        flow_x,
        flow_y,
        foreground_mask=semantic_mask > 0,
        background_mode="foreground_rgb",
    )
    save_event_stream_gif(debug_dir / "event_stream_mask_flow_2.gif", image_rgb, events)
    save_event_stream_gif(debug_dir / "event_stream_mask_flow_black_2.gif", image_rgb, events, background_mode="black")

    stats = save_event_analysis(debug_dir, image_rgb, semantic_mask, blob_map, blob_metadata, events)
    summary = {
        "mode": "semantic_mask_focused_flow",
        "duration_ms": float(duration_ms),
        "magnitude_px": float(magnitude_px),
        "num_events": int(len(events)),
        "region_motion": region_motion,
        "flow": {
            "mean_magnitude_px": float(np.sqrt(flow_x * flow_x + flow_y * flow_y)[semantic_mask > 0].mean()),
            "max_magnitude_px": float(np.sqrt(flow_x * flow_x + flow_y * flow_y).max()),
        },
        "statistics": stats,
    }
    (debug_dir / "debug_summary_2.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    return summary


def build_semantic_region_flow(
    semantic_mask: np.ndarray,
    magnitude_px: float = 4.0,
) -> tuple[np.ndarray, np.ndarray, dict[str, Any]]:
    # Flow convention: flow_x/flow_y are pixel displacements. Positive y moves
    # downward. Each semantic id gets a hand-designed motion pattern for
    # debugging whether events appear on meaningful face structures.
    h, w = semantic_mask.shape
    flow_x = np.zeros((h, w), dtype=np.float32)
    flow_y = np.zeros((h, w), dtype=np.float32)
    region_motion: dict[str, Any] = {}

    def apply_constant(region_id: int, dx: float, dy: float, description: str) -> None:
        mask = semantic_mask == region_id
        if not mask.any():
            return
        flow_x[mask] = float(dx)
        flow_y[mask] = float(dy)
        region_motion[REGION_LABELS[region_id]] = {"dx": float(dx), "dy": float(dy), "description": description}

    # Weak global face drift for skin, then stronger expression-like motions for
    # parts. Nose is almost fixed because rigid nose motion should usually be
    # small compared with eyes, mouth, and brows.
    apply_constant(1, 0.18 * magnitude_px, 0.05 * magnitude_px, "weak skin drift")
    apply_constant(2, 0.00, 0.95 * magnitude_px, "left eye vertical blink-like motion")
    apply_constant(3, 0.00, 0.95 * magnitude_px, "right eye vertical blink-like motion")
    apply_constant(4, 0.04 * magnitude_px, 0.02 * magnitude_px, "nose almost fixed")
    apply_constant(6, 0.00, -0.75 * magnitude_px, "left eyebrow vertical lift")
    apply_constant(7, 0.00, -0.75 * magnitude_px, "right eyebrow vertical lift")
    apply_constant(8, 0.22 * magnitude_px, 0.12 * magnitude_px, "small jaw/contour shift")

    mouth = semantic_mask == 5
    if mouth.any():
        # Mouth uses a spatially varying field, not one constant vector:
        # pixels above/below the mouth center move in opposite vertical
        # directions, producing an open/stretch deformation.
        ys, xs = np.where(mouth)
        cx = float(xs.mean())
        cy = float(ys.mean())
        half_w = max(float(xs.max() - xs.min()) / 2.0, 1.0)
        half_h = max(float(ys.max() - ys.min()) / 2.0, 1.0)
        nx = np.clip((xs.astype(np.float32) - cx) / half_w, -1.0, 1.0)
        ny = np.clip((ys.astype(np.float32) - cy) / half_h, -1.0, 1.0)
        flow_x[ys, xs] = 0.38 * magnitude_px * nx
        flow_y[ys, xs] = 1.10 * magnitude_px * ny
        region_motion["mouth"] = {
            "description": "mouth open/stretch from mouth center",
            "horizontal_stretch_px": float(0.38 * magnitude_px),
            "vertical_stretch_px": float(1.10 * magnitude_px),
        }

    foreground = semantic_mask > 0
    # Smooth only at semantic boundaries. This removes hard flow discontinuities
    # while preserving the intended part-specific motion.
    flow_x = smooth_semantic_boundaries(flow_x, foreground.astype(np.float32))
    flow_y = smooth_semantic_boundaries(flow_y, foreground.astype(np.float32))
    flow_x[~foreground] = 0.0
    flow_y[~foreground] = 0.0
    return flow_x.astype(np.float32), flow_y.astype(np.float32), region_motion


def smooth_semantic_boundaries(field: np.ndarray, foreground: np.ndarray) -> np.ndarray:
    weighted = cv2.GaussianBlur(field * foreground, (0, 0), sigmaX=2.0, sigmaY=2.0)
    weights = cv2.GaussianBlur(foreground, (0, 0), sigmaX=2.0, sigmaY=2.0)
    out = np.zeros_like(field, dtype=np.float32)
    valid = weights > 1e-4
    out[valid] = weighted[valid] / weights[valid]
    return out


def build_arbitrary_face_flow(semantic_mask: np.ndarray, magnitude_px: float = 5.5, seed: int = 7) -> tuple[np.ndarray, np.ndarray]:
    foreground = semantic_mask > 0
    h, w = semantic_mask.shape
    if not foreground.any():
        return np.zeros((h, w), dtype=np.float32), np.zeros((h, w), dtype=np.float32)

    rng = np.random.default_rng(seed)
    ys, xs = np.where(foreground)
    cx = float(xs.mean())
    cy = float(ys.mean())
    scale = max(float(xs.max() - xs.min()), float(ys.max() - ys.min()), 1.0)
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float32)
    nx = (xx - cx) / scale
    ny = (yy - cy) / scale

    global_dx = 0.62 * magnitude_px
    global_dy = -0.20 * magnitude_px
    radial = 1.20 * magnitude_px
    swirl = 0.65 * magnitude_px
    wave_phase = float(rng.uniform(0.0, 2.0 * np.pi))

    flow_x = global_dx + radial * nx - swirl * ny + 0.45 * magnitude_px * np.sin(2.5 * ny + wave_phase)
    flow_y = global_dy + radial * ny + swirl * nx + 0.35 * magnitude_px * np.cos(2.0 * nx - wave_phase)

    # Make eyes and mouth move slightly more than skin/contour so events remain facially interpretable.
    emphasis = np.ones((h, w), dtype=np.float32)
    emphasis[np.isin(semantic_mask, [2, 3, 5])] = 1.45
    emphasis[np.isin(semantic_mask, [6, 7, 8])] = 1.15
    flow_x = flow_x.astype(np.float32) * emphasis
    flow_y = flow_y.astype(np.float32) * emphasis

    foreground_f = foreground.astype(np.float32)
    flow_x, flow_y = normalize_flow_magnitude(flow_x, flow_y, magnitude_px * 1.75)
    flow_x = smooth_with_mask(flow_x, foreground_f)
    flow_y = smooth_with_mask(flow_y, foreground_f)
    flow_x[~foreground] = 0.0
    flow_y[~foreground] = 0.0
    return flow_x.astype(np.float32), flow_y.astype(np.float32)


def normalize_flow_magnitude(flow_x: np.ndarray, flow_y: np.ndarray, max_magnitude: float) -> tuple[np.ndarray, np.ndarray]:
    mag = np.sqrt(flow_x * flow_x + flow_y * flow_y)
    scale = np.ones_like(mag, dtype=np.float32)
    high = mag > max_magnitude
    scale[high] = float(max_magnitude) / np.maximum(mag[high], 1e-6)
    return flow_x * scale, flow_y * scale


def smooth_with_mask(field: np.ndarray, mask: np.ndarray) -> np.ndarray:
    weighted = cv2.GaussianBlur(field * mask, (0, 0), sigmaX=8.0, sigmaY=8.0)
    weights = cv2.GaussianBlur(mask, (0, 0), sigmaX=8.0, sigmaY=8.0)
    out = np.zeros_like(field, dtype=np.float32)
    valid = weights > 1e-4
    out[valid] = weighted[valid] / weights[valid]
    return out


def save_flow_overlay(
    path: Path,
    image_rgb: np.ndarray,
    semantic_mask: np.ndarray,
    flow_x: np.ndarray,
    flow_y: np.ndarray,
) -> None:
    canvas = (image_rgb.astype(np.float32) * 0.45).astype(np.uint8)
    foreground = semantic_mask > 0
    canvas[~foreground] = 0

    h, w = semantic_mask.shape
    stride = max(20, min(h, w) // 22)
    mag = np.sqrt(flow_x * flow_x + flow_y * flow_y)
    max_mag = max(float(mag.max()), 1e-6)
    for y in range(0, h, stride):
        for x in range(0, w, stride):
            if not foreground[y, x]:
                continue
            dx = float(flow_x[y, x])
            dy = float(flow_y[y, x])
            color_strength = int(np.clip(80 + 175 * mag[y, x] / max_mag, 80, 255))
            color = (color_strength, 220, 40)
            end = (
                int(np.clip(round(x + dx * 3.0), 0, w - 1)),
                int(np.clip(round(y + dy * 3.0), 0, h - 1)),
            )
            cv2.arrowedLine(canvas, (x, y), end, color, 2, tipLength=0.35)
    cv2.imwrite(str(path), cv2.cvtColor(canvas, cv2.COLOR_RGB2BGR))


def save_semantic_region_flow_overlay(
    path: Path,
    image_rgb: np.ndarray,
    semantic_mask: np.ndarray,
    flow_x: np.ndarray,
    flow_y: np.ndarray,
) -> None:
    foreground = semantic_mask > 0
    semantic_rgb = PALETTE[semantic_mask].copy()
    base = (image_rgb.astype(np.float32) * 0.25 + semantic_rgb.astype(np.float32) * 0.75).astype(np.uint8)
    base[~foreground] = 0

    h, w = semantic_mask.shape
    stride = max(18, min(h, w) // 26)
    mag = np.sqrt(flow_x * flow_x + flow_y * flow_y)
    max_mag = max(float(mag.max()), 1e-6)
    for region_id, label in REGION_LABELS.items():
        if region_id == 0:
            continue
        ys, xs = np.where(semantic_mask == region_id)
        if len(xs) == 0:
            continue
        x0, x1 = int(xs.min()), int(xs.max())
        y0, y1 = int(ys.min()), int(ys.max())
        color = tuple(int(v) for v in np.clip(PALETTE[region_id].astype(np.int16) + 50, 0, 255).tolist())
        for y in range(y0, y1 + 1, stride):
            for x in range(x0, x1 + 1, stride):
                if semantic_mask[y, x] != region_id:
                    continue
                dx = float(flow_x[y, x])
                dy = float(flow_y[y, x])
                if mag[y, x] <= 1e-4:
                    continue
                thickness = 1 + int(mag[y, x] / max_mag > 0.55)
                end = (
                    int(np.clip(round(x + dx * 3.0), 0, w - 1)),
                    int(np.clip(round(y + dy * 3.0), 0, h - 1)),
                )
                cv2.arrowedLine(base, (x, y), end, color, thickness, tipLength=0.35)
    cv2.imwrite(str(path), cv2.cvtColor(base, cv2.COLOR_RGB2BGR))


def save_flow_magnitude_png(path: Path, semantic_mask: np.ndarray, flow_x: np.ndarray, flow_y: np.ndarray) -> None:
    mag = np.sqrt(flow_x * flow_x + flow_y * flow_y)
    foreground = semantic_mask > 0
    scale = float(np.percentile(mag[foreground], 99.0)) if foreground.any() else float(mag.max())
    normalized = np.clip(mag / max(scale, 1e-6), 0.0, 1.0)
    heat = cv2.applyColorMap((normalized * 255.0).astype(np.uint8), cv2.COLORMAP_TURBO)
    heat = cv2.cvtColor(heat, cv2.COLOR_BGR2RGB)
    heat[~foreground] = 0
    cv2.imwrite(str(path), cv2.cvtColor(heat, cv2.COLOR_RGB2BGR))


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate events from arbitrary synthetic optical flow.")
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--image-path", type=Path, default=None)
    parser.add_argument("--mode", choices=["arbitrary", "semantic-mask"], default="arbitrary")
    parser.add_argument("--duration-ms", type=float, default=140.0)
    parser.add_argument("--magnitude-px", type=float, default=5.5)
    parser.add_argument("--seed", type=int, default=7)
    args = parser.parse_args()

    image_rgb = load_image_for_output(args.output_dir, args.image_path)
    semantic_mask = np.load(args.output_dir / "semantic_mask.npy")
    blob_map = np.load(args.output_dir / "blob_map.npy")
    blob_metadata = json.loads((args.output_dir / "blob_metadata.json").read_text(encoding="utf-8"))
    if args.mode == "semantic-mask":
        summary = run_semantic_mask_focused_flow(
            args.output_dir,
            image_rgb,
            semantic_mask,
            blob_map,
            blob_metadata,
            duration_ms=args.duration_ms,
            magnitude_px=args.magnitude_px,
        )
        out_dir = args.output_dir / "semantic_mask_flow"
    else:
        summary = run_arbitrary_optical_flow(
            args.output_dir,
            image_rgb,
            semantic_mask,
            blob_map,
            blob_metadata,
            duration_ms=args.duration_ms,
            magnitude_px=args.magnitude_px,
            seed=args.seed,
        )
        out_dir = args.output_dir / "arbitrary_optical_flow"
    print(json.dumps({"output_dir": str(out_dir), "num_events": summary["num_events"]}, indent=2))


if __name__ == "__main__":
    main()
