from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import cv2
import numpy as np

from .semantics import PALETTE, REGION_LABELS
from .wflw import wflw_semantic_anchors


ANCHOR_GROUPS = {
    "left_eye": list(range(60, 68)),
    "right_eye": list(range(68, 76)),
    "mouth": list(range(76, 96)),
    "nose": list(range(51, 60)),
    "jaw": list(range(0, 33)),
    "left_eyebrow": list(range(33, 42)),
    "right_eyebrow": list(range(42, 51)),
}

CONTROL_GROUPS = {
    "eye": ["left_eye", "right_eye", "left_eyebrow", "right_eyebrow"],
    "lip": ["mouth"],
    "jaw": ["jaw_or_contour", "skin"],
    "nose": ["nose"],
}

REGION_CONSISTENCY_GROUPS = {
    "ocular_left": ["left_eye", "left_eyebrow"],
    "ocular_right": ["right_eye", "right_eyebrow"],
    "lower_face": ["mouth", "jaw_or_contour"],
    "rigid_midface": ["nose", "skin"],
}


def run_face_feature_adapter(
    image_path: Path,
    landmarks_path: Path,
    semantic_mask_path: Path,
    blob_map_path: Path,
    blob_metadata_path: Path,
    output_dir: Path,
) -> dict[str, Any]:
    image_rgb = load_image_rgb(image_path)
    semantic_mask = np.load(semantic_mask_path)
    blob_map = np.load(blob_map_path)
    blob_metadata = json.loads(blob_metadata_path.read_text(encoding="utf-8"))
    landmarks_payload = load_landmarks_payload(landmarks_path)
    landmarks = normalize_landmarks(landmarks_payload["landmarks"], image_rgb.shape[:2])

    validate_inputs(image_rgb, semantic_mask, blob_map, blob_metadata, landmarks)
    output_dir.mkdir(parents=True, exist_ok=True)

    anchor_state = build_anchor_state(landmarks)
    region_state = build_semantic_region_state(semantic_mask)
    blob_context = build_blob_feature_context(
        image_rgb,
        semantic_mask,
        blob_map,
        blob_metadata,
        anchor_state,
    )
    face_state = {
        "mode": "face_feature_context_only",
        "source_image_path": str(image_path),
        "landmarks_path": str(landmarks_path),
        "image_shape": [int(image_rgb.shape[0]), int(image_rgb.shape[1]), 3],
        "landmark_format": "WFLW_98_xy",
        "normalized_landmarks": landmarks,
        "semantic_region_centroids": region_state,
        "anchor_groups": anchor_state,
        "control_groups": CONTROL_GROUPS,
        "region_consistency_groups": REGION_CONSISTENCY_GROUPS,
        "notes": [
            "No motion is generated by this adapter.",
            "No events are generated by this adapter.",
            "LivePortrait is used only as representation inspiration, not as a motion source.",
        ],
    }
    blob_payload = {
        "mode": "blob_feature_context_only",
        "source_image_path": str(image_path),
        "num_blobs": len(blob_context),
        "control_groups": CONTROL_GROUPS,
        "region_consistency_groups": REGION_CONSISTENCY_GROUPS,
        "blob_feature_context": blob_context,
    }

    (output_dir / "face_feature_state.json").write_text(json.dumps(face_state, indent=2), encoding="utf-8")
    (output_dir / "blob_feature_context.json").write_text(json.dumps(blob_payload, indent=2), encoding="utf-8")
    save_face_feature_overlay(output_dir / "face_feature_overlay.png", image_rgb, semantic_mask, anchor_state)
    save_blob_feature_overlay(output_dir / "blob_feature_overlay.png", image_rgb, blob_map, blob_context)

    summary = {
        "mode": "face_feature_context_only",
        "output_dir": str(output_dir),
        "num_landmarks": len(landmarks),
        "num_blobs": len(blob_context),
        "outputs": [
            "face_feature_state.json",
            "blob_feature_context.json",
            "face_feature_overlay.png",
            "blob_feature_overlay.png",
        ],
    }
    return summary


def load_landmarks_payload(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(payload, list):
        return {"landmarks": payload}
    if isinstance(payload, dict) and "landmarks" in payload:
        return payload
    raise ValueError("landmarks JSON must be a list or an object containing 'landmarks'")


def normalize_landmarks(raw_landmarks: list[dict[str, Any]], image_shape: tuple[int, int]) -> list[dict[str, Any]]:
    h, w = image_shape
    if len(raw_landmarks) < 98:
        raise ValueError(f"WFLW feature adapter expects at least 98 landmarks, got {len(raw_landmarks)}")
    out = []
    for i, point in enumerate(raw_landmarks[:98]):
        x = float(point["x"])
        y = float(point["y"])
        out.append(
            {
                "id": int(point.get("id", i)),
                "x": x,
                "y": y,
                "x_norm": safe_div(x, max(w - 1, 1)),
                "y_norm": safe_div(y, max(h - 1, 1)),
                "visibility": bool(point.get("visibility", True)),
            }
        )
    return out


def build_anchor_state(landmarks: list[dict[str, Any]]) -> dict[str, Any]:
    anchors = wflw_semantic_anchors(landmarks)
    state: dict[str, Any] = {}
    for name, indices in ANCHOR_GROUPS.items():
        pts = np.array([[landmarks[i]["x"], landmarks[i]["y"]] for i in indices], dtype=np.float32)
        center = pts.mean(axis=0)
        bbox = [float(pts[:, 0].min()), float(pts[:, 1].min()), float(pts[:, 0].max()), float(pts[:, 1].max())]
        state[name] = {
            "landmark_ids": [int(i) for i in indices],
            "centroid": [float(center[0]), float(center[1])],
            "bbox": bbox,
            "points": anchors.get(name if name != "jaw" else "jawline", []),
        }
    eye_centers = [state["left_eye"]["centroid"], state["right_eye"]["centroid"]]
    state["eye_pair"] = {
        "source_groups": ["left_eye", "right_eye"],
        "centroid": [float((eye_centers[0][0] + eye_centers[1][0]) * 0.5), float((eye_centers[0][1] + eye_centers[1][1]) * 0.5)],
        "inter_eye_distance": float(np.linalg.norm(np.asarray(eye_centers[0]) - np.asarray(eye_centers[1]))),
    }
    return state


def build_semantic_region_state(semantic_mask: np.ndarray) -> dict[str, Any]:
    state = {}
    for region_id, label in REGION_LABELS.items():
        ys, xs = np.where(semantic_mask == region_id)
        if len(xs) == 0:
            state[label] = {
                "semantic_id": int(region_id),
                "pixel_count": 0,
                "centroid": None,
                "bbox": None,
            }
            continue
        state[label] = {
            "semantic_id": int(region_id),
            "pixel_count": int(len(xs)),
            "centroid": [float(xs.mean()), float(ys.mean())],
            "bbox": [int(xs.min()), int(ys.min()), int(xs.max()), int(ys.max())],
        }
    return state


def build_blob_feature_context(
    image_rgb: np.ndarray,
    semantic_mask: np.ndarray,
    blob_map: np.ndarray,
    blob_metadata: list[dict[str, Any]],
    anchor_state: dict[str, Any],
) -> list[dict[str, Any]]:
    gray = cv2.cvtColor(image_rgb, cv2.COLOR_RGB2GRAY).astype(np.float32)
    gx = cv2.Sobel(gray, cv2.CV_32F, 1, 0, ksize=3)
    gy = cv2.Sobel(gray, cv2.CV_32F, 0, 1, ksize=3)
    grad = np.sqrt(gx * gx + gy * gy)

    rows = []
    for meta in blob_metadata:
        blob_id = int(meta["blob_id"])
        mask = blob_map == blob_id
        if not mask.any():
            continue
        ys, xs = np.where(mask)
        rgb = image_rgb[ys, xs].astype(np.float32)
        centroid = [float(xs.mean()), float(ys.mean())]
        bbox = [int(xs.min()), int(ys.min()), int(xs.max()), int(ys.max())]
        semantic_label = str(meta.get("semantic_label", dominant_semantic_label(semantic_mask[ys, xs])))
        row = {
            "blob_id": blob_id,
            "semantic_id": int(meta.get("semantic_id", int(dominant_value(semantic_mask[ys, xs])))),
            "semantic_label": semantic_label,
            "pixel_count": int(len(xs)),
            "centroid": centroid,
            "bbox": bbox,
            "area_fraction_of_image": safe_div(len(xs), blob_map.size),
            "appearance_stats": {
                "mean_rgb": [float(v) for v in rgb.mean(axis=0)],
                "std_rgb": [float(v) for v in rgb.std(axis=0)],
                "mean_luminance": float(gray[ys, xs].mean()),
                "std_luminance": float(gray[ys, xs].std()),
                "local_texture_strength": float(grad[ys, xs].mean()),
            },
            "anchor_distances": anchor_distances(centroid, anchor_state),
            "control_groups": blob_control_groups(semantic_label),
            "region_consistency_groups": blob_region_consistency_groups(semantic_label),
            "neighbor_blob_ids": [int(v) for v in meta.get("neighbor_blob_ids", [])],
        }
        rows.append(row)
    rows.sort(key=lambda item: int(item["blob_id"]))
    return rows


def anchor_distances(centroid: list[float], anchor_state: dict[str, Any]) -> dict[str, Any]:
    c = np.asarray(centroid, dtype=np.float32)
    mapping = {
        "left_eye": "left_eye",
        "right_eye": "right_eye",
        "eye_pair": "eye_pair",
        "lip": "mouth",
        "nose": "nose",
        "jaw": "jaw",
    }
    distances = {}
    for label, anchor_name in mapping.items():
        anchor = anchor_state.get(anchor_name)
        if not anchor or anchor.get("centroid") is None:
            distances[label] = None
            continue
        ac = np.asarray(anchor["centroid"], dtype=np.float32)
        distances[label] = float(np.linalg.norm(c - ac))
    return distances


def blob_control_groups(semantic_label: str) -> list[str]:
    return [group for group, labels in CONTROL_GROUPS.items() if semantic_label in labels]


def blob_region_consistency_groups(semantic_label: str) -> list[str]:
    return [group for group, labels in REGION_CONSISTENCY_GROUPS.items() if semantic_label in labels]


def save_face_feature_overlay(
    path: Path,
    image_rgb: np.ndarray,
    semantic_mask: np.ndarray,
    anchor_state: dict[str, Any],
) -> None:
    canvas = image_rgb.astype(np.float32) * 0.65 + PALETTE[semantic_mask].astype(np.float32) * 0.35
    canvas = np.clip(canvas, 0, 255).astype(np.uint8)
    for name, anchor in anchor_state.items():
        centroid = anchor.get("centroid")
        if centroid is None:
            continue
        color = anchor_color(name)
        center = (int(round(centroid[0])), int(round(centroid[1])))
        cv2.circle(canvas, center, 5, color, -1)
        cv2.putText(canvas, name, (center[0] + 6, center[1] - 6), cv2.FONT_HERSHEY_SIMPLEX, 0.42, color, 1)
        bbox = anchor.get("bbox")
        if isinstance(bbox, list) and len(bbox) == 4:
            p0 = (int(round(bbox[0])), int(round(bbox[1])))
            p1 = (int(round(bbox[2])), int(round(bbox[3])))
            cv2.rectangle(canvas, p0, p1, color, 1)
    cv2.imwrite(str(path), cv2.cvtColor(canvas, cv2.COLOR_RGB2BGR))


def save_blob_feature_overlay(
    path: Path,
    image_rgb: np.ndarray,
    blob_map: np.ndarray,
    blob_context: list[dict[str, Any]],
) -> None:
    canvas = (image_rgb.astype(np.float32) * 0.45).astype(np.uint8)
    canvas[blob_map == 0] = 0
    for row in blob_context:
        centroid = row["centroid"]
        bbox = row["bbox"]
        color = semantic_color(int(row["semantic_id"]))
        p0 = (int(bbox[0]), int(bbox[1]))
        p1 = (int(bbox[2]), int(bbox[3]))
        center = (int(round(centroid[0])), int(round(centroid[1])))
        cv2.rectangle(canvas, p0, p1, color, 1)
        cv2.circle(canvas, center, 2, color, -1)
        cv2.putText(canvas, str(row["blob_id"]), (center[0] + 3, center[1] + 3), cv2.FONT_HERSHEY_SIMPLEX, 0.35, color, 1)
    cv2.imwrite(str(path), cv2.cvtColor(canvas, cv2.COLOR_RGB2BGR))


def load_image_rgb(path: Path) -> np.ndarray:
    bgr = cv2.imread(str(path), cv2.IMREAD_COLOR)
    if bgr is None:
        raise FileNotFoundError(f"Could not read image: {path}")
    return cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)


def validate_inputs(
    image_rgb: np.ndarray,
    semantic_mask: np.ndarray,
    blob_map: np.ndarray,
    blob_metadata: list[dict[str, Any]],
    landmarks: list[dict[str, Any]],
) -> None:
    if image_rgb.shape[:2] != semantic_mask.shape:
        raise ValueError(f"image and semantic mask shape mismatch: {image_rgb.shape[:2]} vs {semantic_mask.shape}")
    if semantic_mask.shape != blob_map.shape:
        raise ValueError(f"semantic mask and blob map shape mismatch: {semantic_mask.shape} vs {blob_map.shape}")
    if not isinstance(blob_metadata, list):
        raise ValueError("blob_metadata must be a JSON list")
    if len(landmarks) < 98:
        raise ValueError("expected WFLW 98 landmarks")


def dominant_value(values: np.ndarray) -> int:
    unique, counts = np.unique(values, return_counts=True)
    return int(unique[int(np.argmax(counts))])


def dominant_semantic_label(values: np.ndarray) -> str:
    return REGION_LABELS.get(dominant_value(values), "unknown")


def safe_div(numerator: float, denominator: float) -> float:
    if float(denominator) == 0.0:
        return 0.0
    return float(numerator) / float(denominator)


def semantic_color(semantic_id: int) -> tuple[int, int, int]:
    color = PALETTE[int(semantic_id) % len(PALETTE)]
    return int(color[0]), int(color[1]), int(color[2])


def anchor_color(name: str) -> tuple[int, int, int]:
    colors = {
        "left_eye": (40, 180, 255),
        "right_eye": (80, 220, 255),
        "eye_pair": (255, 255, 255),
        "mouth": (255, 80, 100),
        "nose": (80, 220, 120),
        "jaw": (255, 210, 70),
        "left_eyebrow": (180, 90, 240),
        "right_eyebrow": (210, 120, 255),
    }
    return colors.get(name, (240, 240, 240))


def main() -> None:
    parser = argparse.ArgumentParser(description="Prepare face/blob feature context for later motion prompting.")
    parser.add_argument("--image", type=Path, required=True)
    parser.add_argument("--landmarks", type=Path, required=True)
    parser.add_argument("--semantic-mask", type=Path, required=True)
    parser.add_argument("--blob-map", type=Path, required=True)
    parser.add_argument("--blob-metadata", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()

    summary = run_face_feature_adapter(
        image_path=args.image,
        landmarks_path=args.landmarks,
        semantic_mask_path=args.semantic_mask,
        blob_map_path=args.blob_map,
        blob_metadata_path=args.blob_metadata,
        output_dir=args.output_dir,
    )
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
